import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/Components/Navbar";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
