import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/Components/Navbar";
import Providers from "./Providers";
import NavbarWrapper from "./Components/NavbarWrapper";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const path = typeof window !== "undefined" ? window.location.pathname : "";
  // const showNavbar = !path.startsWith("/dashboard");
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <Providers>
          <NavbarWrapper></NavbarWrapper>
          {children}
        </Providers>
      </body>
    </html>
  );
}
